# Site settings
title: "Tor Is Here"
email: kittikorn.a@gmail.com
description: This blog's goal is to record the challenging topic about iOS, Swift and Python, that I encountered and make them easy to understand as possible. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tor.zone" # the base hostname & protocol for your site
twitter_username: KAriyasuk
github_username:  TorIsHere

# Build settings
markdown: kramdown
