# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tor is Here
email: kittikorn.a@gmail.com
description: This is my house
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tor.zone" # the base hostname & protocol for your site
twitter_username: KAriyasuk
github_username:  TorIsHere

# Build settings
markdown: kramdown
